
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://frlpuhozzbcmttahbskb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZybHB1aG96emJjbXR0YWhic2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzY3ODYsImV4cCI6MjA2MjY1Mjc4Nn0.4koW9580qWtbs4Syesh3XOQecT_DhNXw77DqjGSogDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
  }
});
